Spring:
  Application:
    name: Elegant_class_project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hoes_at_job?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto : none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
  logging:
    level:
      root: INFO
      java.resources.db.migration: DEBUG